import Head from 'next/head'
import Image from 'next/image'
import { Edu_NSW_ACT_Foundation, Inter } from 'next/font/google'
import _Home from '@/components/home/Home'
import About from '@/components/about/About'
import Skills from '@/components/skills/Skills'
import Education from '@/components/education/Education'
import Contact from '@/components/contact/Contact'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'/>
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"/>
      </Head>
      
      <main >
	  <_Home/>
	  <About/>
	  <Skills/>
	  <Education/>
	  <Contact/>
    
    {/* <Home/> */}
    {/* <About/> */}
    {/* <Skills/> */}
    {/* <Education/> */}
    {/* <Contact/> */}

    
 
      </main>
    </>
  )
}
